### ISSUE TITLE
Streamlit Issue Docker Image not found

### ISSUE THREAD

**Issue by birdup000** [localagi/AGiXT-docker#1]
![image](https://github.com/localagi/AGiXT-docker/assets/34012548/b07eb5cc-d954-406e-aba3-a03615e9740e)

**Comment by localagi** [comment]
On it - moved to pipeline v3, currently testing

**Comment by localagi** [comment]
Running on odroid-n2 at this moment. `arm64`arch. Can create an agent with gpt4free. Agent answers against request `hi`
